Does my coding partner follow JS best practices?
Mutai-Gilbert/To-Do-List-Review pull request #1
Opened 2023-02-27 13:00 UTC by Mutai-Gilbert

This pull request is created for a code review between coding partners to see it follows best coding practices.

Checking the quality of the code. The following will be checked:

1. JavaScript best practices.
2. DRY, KISS, and YAGNI.
3. HTML & CSS best practices

2023-02-27 14:07 UTC, stephenkati requested changes
**Hi @Mutai-Gilbert,**
#
**Highlights!**
Good code organization and working app :heavy_check_mark:
Descriptive README:heavy_check_mark:
Linters :heavy_check_mark: 
DRY code :heavy_check_mark:
#
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! :tada:

### **Status: Approved :heavy_check_mark:**
Cheers, and Happy coding!:clap::clap::clap:
#
**Optional suggestions**
Every comment with the **[OPTIONAL]** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-27 14:07 UTC, stephenkati commented on src/index.js
> +  }
Make use of JavaScript ES6, employ use of arrow function functions to make your code easy to read and maintain

2023-02-27 14:07 UTC, stephenkati commented on src/index.js
> +    // remove the task from the DOM
Remove comments, your code should be self-explanatory hence no need to add comments

2023-02-27 17:34 UTC, Mutai-Gilbert commented on src/index.js
> +  }
Thank you

2023-02-27 17:35 UTC, Mutai-Gilbert commented on src/index.js
> +    // remove the task from the DOM
Done

2023-02-27 17:36 UTC, merged

2023-05-26 04:17 UTC, stephenkati commented on src/index.js
> +  }
You are welcome